@echo off
setlocal
cd /d "%~dp0"

set "FNA3D_FORCE_DRIVER=D3D11"
set "XNATOFNA_DISPLAY_FULLSCREEN=0"
set "XBLIG_FULLSCREEN=0"
set "XBLIG_BYPASS_APPLYWINDOWCHANGES_HOOK=0"
set "XBLIG_KEYBOARD_GAMEPAD_DISABLE="

set "XNATOFNA_DISPLAY_SIZE="
set "XNATOFNA_DISPLAY_WIDTH="
set "XNATOFNA_DISPLAY_HEIGHT="
set "XBLIG_DISPLAY_SIZE="
set "XBLIG_DISPLAY_WIDTH="
set "XBLIG_DISPLAY_HEIGHT="

"%~dp0ZombieEstate.exe"
endlocal
